#1. https://hub.docker.com/_/mysql/
#2. https://hub.docker.com/_/redis/
#3. https://hub.docker.com/r/hyness/spring-cloud-config-server/
#4. custom eureka server (1.6.2) available at https://github.com/jphilippeplante/eureka-server.git
#5. custom hystrix and turbine (via rabbitmq) (1.0.0) https://github.com/jphilippeplante/hystrix-turbine
#6. https://hub.docker.com/r/library/rabbitmq
version: '2'
services:
  mysql:
    image: "mysql:latest"
    ports:
     - "3306:3306"
    volumes:
     - /tmp/mysql-data:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=my-secret-pw
  redis:
    image: "redis:alpine"
    environment:
      - REDIS_APPENDFSYNC=always
      - REDIS_APPENDONLY=yes
      - REDIS_PASSWORD=password
    ports:
     - "6379:6379"
    volumes:
     - /tmp/redis-data:/data
  configserver:
    image: "hyness/spring-cloud-config-server:latest"
    ports:
     - "8888:8888"
    volumes:
     - ./configurations/config-server.yml:/config/application.yml
  eureka:
    build: https://github.com/jphilippeplante/eureka-server.git
    image: "eureka-server:1.6.2"
    ports:
     - "8761:8761"
    links:
     - configserver:configserver
    volumes:
     - ./configurations/eureka-server.yml:/config/application.yml
  hystrix-turbine:
    build: https://github.com/jphilippeplante/hystrix-turbine.git
    image: "hystrix-turbine:1.0.0"
    depends_on:
      - rabbitmq
    links:
      - rabbitmq:rabbitmq
    ports:
      - "7979:7979"
      - "8989:8989"
    volumes:
     - ./configurations/hystrix-server.yml:/config/application.yml
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
